# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
